FROM redhat/ubi8
RUN yum install java -y
RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz /opt/tomcat
RUN tar -xvzf apache-tomcat-9.0.85.tar.gz
RUN mv apache-tomcat-9.0.85/* /opt/tomcat
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]


############
docker build -t viswkum/abcd:mytomcat .


https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz